export const PROFILE_TEXT = {
  backLabel: "Back to Home",
  headerTitle: "Profile dashboard",
  headerSubtitle: "Manage your details, moderation, and updates in one place.",
  editLabel: "Edit Profile",
  saveLabel: "Save Changes",
  cancelLabel: "Cancel",
  missingZipcodeMessage:
    "Your zipcode is missing. Add it now to complete your profile.",
  updateZipcodeLabel: "Update Zipcode",
  profileDetailsTitle: "Profile details",
  notificationsTitle: "Notifications",
  notificationsBadge: "Latest",
  notificationsLoading: "Loading notifications...",
  noNotifications: "No notifications yet.",
  moderationQueueTitle: "Moderation queue",
  moderationQueueBadge: "Pending",
  flagsLoading: "Loading flags...",
  noPendingFlags: "No pending flags right now.",
  acknowledgeLabel: "Acknowledge",
  seenFlagsTitle: "Seen flags",
  seenFlagsBadge: "Seen",
  seenFlagsLoading: "Loading seen flags...",
  noSeenFlags: "No seen flags yet.",
  accountStatusTitle: "Account status",
  quickActionsTitle: "Quick actions",
  quickEditLabel: "Edit profile",
  quickBrowseLabel: "Browse posts",
} as const;
